### ISSUE TITLE
Bug with import module rospy on stable version of clever image

### ISSUE THREAD

**Issue by xsestech** [CopterExpress/clever#70]
I am using verion v0.8.1 of clever image.
I got this error
```
Traceback (most recent call last):
  File "py.py", line 1, in <module>
    import rospy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/std_msgs/msg/_Bool.py", line 5, in <module>
    import genpy
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml
ImportError: No module named 'yaml'
```
This is python script
```
import rospy

rospy.init_node('my_ros_node')  # имя ROS-ноды

rospy.spin()  # входим в бесонечный цикл..
```

![2018-10-09 15_51_24](https://user-images.githubusercontent.com/29453203/46670601-43c41380-cbdb-11e8-86f3-67880b6d4332.png)

**Comment by xsestech** [comment]
I was using `sudo py.py`, but rospy isn't working by sudo.
